version: '3.8'

services:
  app:
    image: appship
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:3000"
    env_file:
      - .env.local
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
    command: npm start